# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: technicodes
# "service" is the name of this project. This will also be added to your AWS resource names.
service: userService

provider:
  name: aws
  runtime: nodejs20.x
functions:
  signup:
    handler: app/handler.SignupHandler
    events:
      - httpApi:
          path: /signup
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript
